using System;
using System.Collections.Generic;
using System.Linq;
using InnoEngine.Reflection;
using InnoEngine.Serialization;
using InnoEngine.Settings;

namespace Inno.Rendering2D;

/// <summary>Defines one stable artist-facing sprite sorting layer.</summary>
public struct SortingLayer2DDefinition
{
    /// <summary>Creates a sorting-layer definition.</summary>
    /// <param name="id">Plugin-qualified stable identity.</param>
    /// <param name="name">Artist-facing display name.</param>
    /// <param name="order">Ascending layer order.</param>
    public SortingLayer2DDefinition(string id, string name, int order)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(id);
        ArgumentException.ThrowIfNullOrWhiteSpace(name);
        this.id = id.Trim();
        this.name = name.Trim();
        this.order = order;
    }

    /// <summary>Gets or sets the plugin-qualified stable identity.</summary>
    public string id { get; set; }

    /// <summary>Gets or sets the artist-facing display name.</summary>
    public string name { get; set; }

    /// <summary>Gets or sets the ascending layer order.</summary>
    public int order { get; set; }
}

/// <summary>Stores project-wide limits and stable sorting-layer definitions for the 2D renderer.</summary>
[StableTypeId("26a75fc8-54bc-4558-9e12-a8035b9176d6")]
[ProjectSettingDefinition("inno.rendering.2d")]
public sealed class Rendering2DProjectSettings : ISerializable
{
    private SortingLayer2DDefinition[] m_sortingLayers =
    [
        new SortingLayer2DDefinition("inno.rendering.2d.default", "Default", 0)
    ];

    /// <summary>Gets the stable project setting identity.</summary>
    public static ProjectSettingId id => new("inno.rendering.2d");

    /// <summary>
    /// Gets or sets the project-wide pixels represented by one world unit for sprite defaults and pixel-perfect cameras.
    /// </summary>
    [SerializableProperty]
    public float defaultPixelsPerUnit { get; set; } = 100f;

    /// <summary>Gets or sets the maximum generated quads accepted in one request.</summary>
    [SerializableProperty]
    public int maximumQuadsPerFrame { get; set; } = 262_144;

    /// <summary>Gets or sets the maximum adjacent quads grouped into one draw batch.</summary>
    [SerializableProperty]
    public int maximumQuadsPerBatch { get; set; } = 16_384;

    /// <summary>Gets or sets the maximum quads generated by one tiled sprite.</summary>
    [SerializableProperty]
    public int maximumTiledSpriteQuads { get; set; } = 4_096;

    /// <summary>Gets or sets stable sorting layers in arbitrary authoring order.</summary>
    [SerializableProperty]
    public SortingLayer2DDefinition[] sortingLayers
    {
        get => m_sortingLayers;
        set => m_sortingLayers = value?.ToArray() ?? [];
    }

    /// <summary>Gets the effective order of a stable sorting layer.</summary>
    /// <param name="sortingLayerId">Stable layer identity.</param>
    /// <returns>The configured order, or zero when the layer is undefined.</returns>
    public int GetSortingLayerOrder(string sortingLayerId)
    {
        foreach (SortingLayer2DDefinition candidate in m_sortingLayers)
        {
            if (string.Equals(candidate.id, sortingLayerId, StringComparison.Ordinal))
                return candidate.order;
        }
        return 0;
    }

    /// <summary>Replaces all sorting layers after validating stable identities.</summary>
    /// <param name="definitions">Complete sorting-layer set.</param>
    /// <exception cref="ArgumentException">Thrown when an ID is empty or duplicated.</exception>
    public void SetSortingLayers(IEnumerable<SortingLayer2DDefinition> definitions)
    {
        ArgumentNullException.ThrowIfNull(definitions);
        SortingLayer2DDefinition[] values = definitions.ToArray();
        if (values.Any(static value => string.IsNullOrWhiteSpace(value.id)))
            throw new ArgumentException("Sorting-layer IDs cannot be empty.", nameof(definitions));
        if (values.Select(static value => value.id).Distinct(StringComparer.Ordinal).Count() != values.Length)
            throw new ArgumentException("Sorting-layer IDs must be unique.", nameof(definitions));
        m_sortingLayers = values;
    }
}
